-- ============================================================
-- CASINO - RULETA DE LA FORTUNA (1 TIRADA / HORA)
-- El premio y el cooldown se deciden en PostgreSQL.
-- No modifica el saldo inicial ni las reglas de otros juegos.
-- ============================================================

create table if not exists public.fortune_spins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reward_code text not null,
  reward_label text not null,
  reward_type text not null check (reward_type in ('cr','xp')),
  reward_cr integer not null default 0,
  reward_xp integer not null default 0,
  spun_at timestamptz not null default now()
);

create index if not exists fortune_spins_user_time_idx
on public.fortune_spins(user_id, spun_at desc);

alter table public.fortune_spins enable row level security;
revoke all on table public.fortune_spins from public, anon, authenticated;

-- ============================================================
-- ESTADO DE LA RULETA
-- ============================================================

create or replace function public.fortune_status(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.app_user_id(p_token);
  v_last public.fortune_spins%rowtype;
  v_next timestamptz;
begin
  if v_uid is null then
    raise exception 'Sesión no válida';
  end if;

  select *
  into v_last
  from public.fortune_spins fs
  where fs.user_id = v_uid
  order by fs.spun_at desc
  limit 1;

  v_next := case
    when v_last.spun_at is null then now()
    else v_last.spun_at + interval '1 hour'
  end;

  return jsonb_build_object(
    'can_spin', v_next <= now(),
    'last_spin_at', v_last.spun_at,
    'next_spin_at', v_next,
    'last_reward_code', v_last.reward_code,
    'last_reward_label', v_last.reward_label
  );
end;
$$;

-- ============================================================
-- GIRAR
-- Probabilidades elegidas para que la tirada se sienta generosa
-- sin inflar demasiado la economía.
--
-- +5 CR   61%
-- +10 CR  14%
-- +15 CR   5%
-- +20 CR   2,6%
-- +50 CR   0,2%
-- +20 XP  10%
-- +50 XP   7,2%
-- ============================================================

create or replace function public.fortune_spin(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.app_user_id(p_token);
  v_now timestamptz := now();
  v_last timestamptz;
  v_roll numeric;
  v_code text;
  v_label text;
  v_type text;
  v_cr integer := 0;
  v_xp integer := 0;
  v_coins integer;
  v_total_xp integer;
  v_level integer;
begin
  if v_uid is null then
    raise exception 'Sesión no válida';
  end if;

  -- Bloqueamos el perfil para que dos clicks simultáneos no produzcan
  -- dos premios antes de que el navegador pueda reaccionar.
  perform 1
  from public.profiles p
  where p.id = v_uid
  for update;

  if not found then
    raise exception 'No existe tu perfil';
  end if;

  select max(fs.spun_at)
  into v_last
  from public.fortune_spins fs
  where fs.user_id = v_uid;

  if v_last is not null and v_last + interval '1 hour' > v_now then
    raise exception using
      message = format(
        'Aún no puedes girar. Te quedan %s segundos.',
        ceil(extract(epoch from ((v_last + interval '1 hour') - v_now)))::integer
      );
  end if;

  v_roll := pg_catalog.random();

  if v_roll < 0.61 then
    v_code := 'cr5';
    v_label := '+5 CR';
    v_type := 'cr';
    v_cr := 5;
  elsif v_roll < 0.75 then
    v_code := 'cr10';
    v_label := '+10 CR';
    v_type := 'cr';
    v_cr := 10;
  elsif v_roll < 0.80 then
    v_code := 'cr15';
    v_label := '+15 CR';
    v_type := 'cr';
    v_cr := 15;
  elsif v_roll < 0.826 then
    v_code := 'cr20';
    v_label := '+20 CR';
    v_type := 'cr';
    v_cr := 20;
  elsif v_roll < 0.828 then
    v_code := 'cr50';
    v_label := '+50 CR';
    v_type := 'cr';
    v_cr := 50;
  elsif v_roll < 0.928 then
    v_code := 'xp20';
    v_label := '+20 XP';
    v_type := 'xp';
    v_xp := 20;
  else
    v_code := 'xp50';
    v_label := '+50 XP';
    v_type := 'xp';
    v_xp := 50;
  end if;

  update public.profiles
  set
    coins = coins + v_cr,
    xp = xp + v_xp,
    level = public.level_for_xp(xp + v_xp)
  where id = v_uid
  returning coins, xp, level
  into v_coins, v_total_xp, v_level;

  insert into public.fortune_spins (
    user_id,
    reward_code,
    reward_label,
    reward_type,
    reward_cr,
    reward_xp,
    spun_at
  )
  values (
    v_uid,
    v_code,
    v_label,
    v_type,
    v_cr,
    v_xp,
    v_now
  );

  return jsonb_build_object(
    'reward_code', v_code,
    'reward_label', v_label,
    'reward_type', v_type,
    'reward_cr', v_cr,
    'reward_xp', v_xp,
    'coins', v_coins,
    'xp', v_total_xp,
    'level', v_level,
    'next_spin_at', v_now + interval '1 hour'
  );
end;
$$;

revoke all on function public.fortune_status(text) from public, anon, authenticated;
revoke all on function public.fortune_spin(text) from public, anon, authenticated;

grant execute on function public.fortune_status(text) to anon;
grant execute on function public.fortune_spin(text) to anon;

notify pgrst, 'reload schema';
